name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6am UTC
  push:
    branches:
      - main
      - '*.x'
    tags:
      - '*'
  pull_request:
    # We also want this workflow triggered if the `jsonschema` label is
    # added or present when PR is updated
    types:
      - synchronize
      - labeled


# Only cancel in-progress jobs or runs for the current workflow
#   This cancels the already triggered workflows for a specific PR without canceling
#   other instances of this workflow (other PRs, scheduled triggers, etc) when something
#   within that PR re-triggers this CI
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1
  core:
    needs: [pre-commit]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v2
    with:
      submodules: false
      # Any env name which does not start with `pyXY` will use this Python version.
      default_python: '3.10'
      envs: |
        - linux: py313
        - linux: py312
        - linux: py311
        - linux: py310
        - linux: py39

  dev:
    needs: [core]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v2
    with:
      submodules: false
      # Any env name which does not start with `pyXY` will use this Python version.
      default_python: '3.11'
      envs: |
        - linux: py314
          python-version: '3.14-dev'
        # separate pytest so a failure here doesn't cause the whole suite to fail
        - linux: py311-pytestdev
